# Generated by Django 6.0 on 2025-12-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0002_alter_post_options_post_artist_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
