# Generated by Django 6.0 on 2026-01-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0003_remove_post_artist_remove_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='a_post.tag'),
        ),
    ]
