# Generated by Django 6.0 on 2026-01-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
