# Generated by Django 6.0 on 2026-01-16 11:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0011_likedreply_reply_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='icons/'),
        ),
    ]
